/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Voice_ssoRouteImport } from './routes/voice_sso'
import { Route as VoiceSsoRouteImport } from './routes/voice-sso'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SdksRouteImport } from './routes/sdks'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardWorkflowsRouteImport } from './routes/_authenticated/dashboard/workflows'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardSchedulesRouteImport } from './routes/_authenticated/dashboard/schedules'
import { Route as AuthenticatedDashboardQaRouteImport } from './routes/_authenticated/dashboard/qa'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardPhoneNumbersRouteImport } from './routes/_authenticated/dashboard/phone-numbers'
import { Route as AuthenticatedDashboardOutboundRouteImport } from './routes/_authenticated/dashboard/outbound'
import { Route as AuthenticatedDashboardKnowledgeBaseRouteImport } from './routes/_authenticated/dashboard/knowledge-base'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard/integrations'
import { Route as AuthenticatedDashboardChatHistoryRouteImport } from './routes/_authenticated/dashboard/chat-history'
import { Route as AuthenticatedDashboardCallsRouteImport } from './routes/_authenticated/dashboard/calls'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard/billing'
import { Route as AuthenticatedDashboardBatchCallRouteImport } from './routes/_authenticated/dashboard/batch-call'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard/analytics'
import { Route as AuthenticatedDashboardAlertingRouteImport } from './routes/_authenticated/dashboard/alerting'
import { Route as AuthenticatedDashboardAgentsIndexRouteImport } from './routes/_authenticated/dashboard/agents/index'
import { Route as AuthenticatedDashboardSchedulesIdRouteImport } from './routes/_authenticated/dashboard/schedules.$id'
import { Route as AuthenticatedDashboardCallsCallIdRouteImport } from './routes/_authenticated/dashboard/calls/$callId'
import { Route as AuthenticatedDashboardAgentsNewRouteImport } from './routes/_authenticated/dashboard/agents/new'

const Voice_ssoRoute = Voice_ssoRouteImport.update({
  id: '/voice_sso',
  path: '/voice_sso',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceSsoRoute = VoiceSsoRouteImport.update({
  id: '/voice-sso',
  path: '/voice-sso',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SdksRoute = SdksRouteImport.update({
  id: '/sdks',
  path: '/sdks',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardWorkflowsRoute =
  AuthenticatedDashboardWorkflowsRouteImport.update({
    id: '/dashboard/workflows',
    path: '/dashboard/workflows',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSchedulesRoute =
  AuthenticatedDashboardSchedulesRouteImport.update({
    id: '/dashboard/schedules',
    path: '/dashboard/schedules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardQaRoute =
  AuthenticatedDashboardQaRouteImport.update({
    id: '/dashboard/qa',
    path: '/dashboard/qa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardPhoneNumbersRoute =
  AuthenticatedDashboardPhoneNumbersRouteImport.update({
    id: '/dashboard/phone-numbers',
    path: '/dashboard/phone-numbers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardOutboundRoute =
  AuthenticatedDashboardOutboundRouteImport.update({
    id: '/dashboard/outbound',
    path: '/dashboard/outbound',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseRoute =
  AuthenticatedDashboardKnowledgeBaseRouteImport.update({
    id: '/dashboard/knowledge-base',
    path: '/dashboard/knowledge-base',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/dashboard/integrations',
    path: '/dashboard/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardChatHistoryRoute =
  AuthenticatedDashboardChatHistoryRouteImport.update({
    id: '/dashboard/chat-history',
    path: '/dashboard/chat-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCallsRoute =
  AuthenticatedDashboardCallsRouteImport.update({
    id: '/dashboard/calls',
    path: '/dashboard/calls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/dashboard/billing',
    path: '/dashboard/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBatchCallRoute =
  AuthenticatedDashboardBatchCallRouteImport.update({
    id: '/dashboard/batch-call',
    path: '/dashboard/batch-call',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/dashboard/analytics',
    path: '/dashboard/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAlertingRoute =
  AuthenticatedDashboardAlertingRouteImport.update({
    id: '/dashboard/alerting',
    path: '/dashboard/alerting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAgentsIndexRoute =
  AuthenticatedDashboardAgentsIndexRouteImport.update({
    id: '/dashboard/agents/',
    path: '/dashboard/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSchedulesIdRoute =
  AuthenticatedDashboardSchedulesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardSchedulesRoute,
  } as any)
const AuthenticatedDashboardCallsCallIdRoute =
  AuthenticatedDashboardCallsCallIdRouteImport.update({
    id: '/$callId',
    path: '/$callId',
    getParentRoute: () => AuthenticatedDashboardCallsRoute,
  } as any)
const AuthenticatedDashboardAgentsNewRoute =
  AuthenticatedDashboardAgentsNewRouteImport.update({
    id: '/dashboard/agents/new',
    path: '/dashboard/agents/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/docs': typeof DocsRoute
  '/dpa': typeof DpaRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/sdks': typeof SdksRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/voice-sso': typeof VoiceSsoRoute
  '/voice_sso': typeof Voice_ssoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/alerting': typeof AuthenticatedDashboardAlertingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/batch-call': typeof AuthenticatedDashboardBatchCallRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsRouteWithChildren
  '/dashboard/chat-history': typeof AuthenticatedDashboardChatHistoryRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/knowledge-base': typeof AuthenticatedDashboardKnowledgeBaseRoute
  '/dashboard/outbound': typeof AuthenticatedDashboardOutboundRoute
  '/dashboard/phone-numbers': typeof AuthenticatedDashboardPhoneNumbersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/qa': typeof AuthenticatedDashboardQaRoute
  '/dashboard/schedules': typeof AuthenticatedDashboardSchedulesRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/workflows': typeof AuthenticatedDashboardWorkflowsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/agents/new': typeof AuthenticatedDashboardAgentsNewRoute
  '/dashboard/calls/$callId': typeof AuthenticatedDashboardCallsCallIdRoute
  '/dashboard/schedules/$id': typeof AuthenticatedDashboardSchedulesIdRoute
  '/dashboard/agents/': typeof AuthenticatedDashboardAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/docs': typeof DocsRoute
  '/dpa': typeof DpaRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/sdks': typeof SdksRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/voice-sso': typeof VoiceSsoRoute
  '/voice_sso': typeof Voice_ssoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/alerting': typeof AuthenticatedDashboardAlertingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/batch-call': typeof AuthenticatedDashboardBatchCallRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsRouteWithChildren
  '/dashboard/chat-history': typeof AuthenticatedDashboardChatHistoryRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/knowledge-base': typeof AuthenticatedDashboardKnowledgeBaseRoute
  '/dashboard/outbound': typeof AuthenticatedDashboardOutboundRoute
  '/dashboard/phone-numbers': typeof AuthenticatedDashboardPhoneNumbersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/qa': typeof AuthenticatedDashboardQaRoute
  '/dashboard/schedules': typeof AuthenticatedDashboardSchedulesRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/workflows': typeof AuthenticatedDashboardWorkflowsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/agents/new': typeof AuthenticatedDashboardAgentsNewRoute
  '/dashboard/calls/$callId': typeof AuthenticatedDashboardCallsCallIdRoute
  '/dashboard/schedules/$id': typeof AuthenticatedDashboardSchedulesIdRoute
  '/dashboard/agents': typeof AuthenticatedDashboardAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/docs': typeof DocsRoute
  '/dpa': typeof DpaRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/sdks': typeof SdksRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/voice-sso': typeof VoiceSsoRoute
  '/voice_sso': typeof Voice_ssoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/dashboard/alerting': typeof AuthenticatedDashboardAlertingRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/batch-call': typeof AuthenticatedDashboardBatchCallRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/calls': typeof AuthenticatedDashboardCallsRouteWithChildren
  '/_authenticated/dashboard/chat-history': typeof AuthenticatedDashboardChatHistoryRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/knowledge-base': typeof AuthenticatedDashboardKnowledgeBaseRoute
  '/_authenticated/dashboard/outbound': typeof AuthenticatedDashboardOutboundRoute
  '/_authenticated/dashboard/phone-numbers': typeof AuthenticatedDashboardPhoneNumbersRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/qa': typeof AuthenticatedDashboardQaRoute
  '/_authenticated/dashboard/schedules': typeof AuthenticatedDashboardSchedulesRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/workflows': typeof AuthenticatedDashboardWorkflowsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/agents/new': typeof AuthenticatedDashboardAgentsNewRoute
  '/_authenticated/dashboard/calls/$callId': typeof AuthenticatedDashboardCallsCallIdRoute
  '/_authenticated/dashboard/schedules/$id': typeof AuthenticatedDashboardSchedulesIdRoute
  '/_authenticated/dashboard/agents/': typeof AuthenticatedDashboardAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-reference'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/docs'
    | '/dpa'
    | '/features'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/roadmap'
    | '/sdks'
    | '/security'
    | '/signup'
    | '/status'
    | '/terms'
    | '/voice-sso'
    | '/voice_sso'
    | '/auth/callback'
    | '/dashboard/alerting'
    | '/dashboard/analytics'
    | '/dashboard/batch-call'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/chat-history'
    | '/dashboard/integrations'
    | '/dashboard/knowledge-base'
    | '/dashboard/outbound'
    | '/dashboard/phone-numbers'
    | '/dashboard/profile'
    | '/dashboard/qa'
    | '/dashboard/schedules'
    | '/dashboard/settings'
    | '/dashboard/workflows'
    | '/dashboard/'
    | '/dashboard/agents/new'
    | '/dashboard/calls/$callId'
    | '/dashboard/schedules/$id'
    | '/dashboard/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-reference'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/docs'
    | '/dpa'
    | '/features'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/roadmap'
    | '/sdks'
    | '/security'
    | '/signup'
    | '/status'
    | '/terms'
    | '/voice-sso'
    | '/voice_sso'
    | '/auth/callback'
    | '/dashboard/alerting'
    | '/dashboard/analytics'
    | '/dashboard/batch-call'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/chat-history'
    | '/dashboard/integrations'
    | '/dashboard/knowledge-base'
    | '/dashboard/outbound'
    | '/dashboard/phone-numbers'
    | '/dashboard/profile'
    | '/dashboard/qa'
    | '/dashboard/schedules'
    | '/dashboard/settings'
    | '/dashboard/workflows'
    | '/dashboard'
    | '/dashboard/agents/new'
    | '/dashboard/calls/$callId'
    | '/dashboard/schedules/$id'
    | '/dashboard/agents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/api-reference'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/docs'
    | '/dpa'
    | '/features'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/roadmap'
    | '/sdks'
    | '/security'
    | '/signup'
    | '/status'
    | '/terms'
    | '/voice-sso'
    | '/voice_sso'
    | '/auth/callback'
    | '/_authenticated/dashboard/alerting'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/batch-call'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/calls'
    | '/_authenticated/dashboard/chat-history'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/knowledge-base'
    | '/_authenticated/dashboard/outbound'
    | '/_authenticated/dashboard/phone-numbers'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/qa'
    | '/_authenticated/dashboard/schedules'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/workflows'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/agents/new'
    | '/_authenticated/dashboard/calls/$callId'
    | '/_authenticated/dashboard/schedules/$id'
    | '/_authenticated/dashboard/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  DocsRoute: typeof DocsRoute
  DpaRoute: typeof DpaRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  SdksRoute: typeof SdksRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  VoiceSsoRoute: typeof VoiceSsoRoute
  Voice_ssoRoute: typeof Voice_ssoRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice_sso': {
      id: '/voice_sso'
      path: '/voice_sso'
      fullPath: '/voice_sso'
      preLoaderRoute: typeof Voice_ssoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-sso': {
      id: '/voice-sso'
      path: '/voice-sso'
      fullPath: '/voice-sso'
      preLoaderRoute: typeof VoiceSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdks': {
      id: '/sdks'
      path: '/sdks'
      fullPath: '/sdks'
      preLoaderRoute: typeof SdksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/workflows': {
      id: '/_authenticated/dashboard/workflows'
      path: '/dashboard/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/schedules': {
      id: '/_authenticated/dashboard/schedules'
      path: '/dashboard/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof AuthenticatedDashboardSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/qa': {
      id: '/_authenticated/dashboard/qa'
      path: '/dashboard/qa'
      fullPath: '/dashboard/qa'
      preLoaderRoute: typeof AuthenticatedDashboardQaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/phone-numbers': {
      id: '/_authenticated/dashboard/phone-numbers'
      path: '/dashboard/phone-numbers'
      fullPath: '/dashboard/phone-numbers'
      preLoaderRoute: typeof AuthenticatedDashboardPhoneNumbersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/outbound': {
      id: '/_authenticated/dashboard/outbound'
      path: '/dashboard/outbound'
      fullPath: '/dashboard/outbound'
      preLoaderRoute: typeof AuthenticatedDashboardOutboundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/knowledge-base': {
      id: '/_authenticated/dashboard/knowledge-base'
      path: '/dashboard/knowledge-base'
      fullPath: '/dashboard/knowledge-base'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/dashboard/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/chat-history': {
      id: '/_authenticated/dashboard/chat-history'
      path: '/dashboard/chat-history'
      fullPath: '/dashboard/chat-history'
      preLoaderRoute: typeof AuthenticatedDashboardChatHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/calls': {
      id: '/_authenticated/dashboard/calls'
      path: '/dashboard/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof AuthenticatedDashboardCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/batch-call': {
      id: '/_authenticated/dashboard/batch-call'
      path: '/dashboard/batch-call'
      fullPath: '/dashboard/batch-call'
      preLoaderRoute: typeof AuthenticatedDashboardBatchCallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/alerting': {
      id: '/_authenticated/dashboard/alerting'
      path: '/dashboard/alerting'
      fullPath: '/dashboard/alerting'
      preLoaderRoute: typeof AuthenticatedDashboardAlertingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/agents/': {
      id: '/_authenticated/dashboard/agents/'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/schedules/$id': {
      id: '/_authenticated/dashboard/schedules/$id'
      path: '/$id'
      fullPath: '/dashboard/schedules/$id'
      preLoaderRoute: typeof AuthenticatedDashboardSchedulesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardSchedulesRoute
    }
    '/_authenticated/dashboard/calls/$callId': {
      id: '/_authenticated/dashboard/calls/$callId'
      path: '/$callId'
      fullPath: '/dashboard/calls/$callId'
      preLoaderRoute: typeof AuthenticatedDashboardCallsCallIdRouteImport
      parentRoute: typeof AuthenticatedDashboardCallsRoute
    }
    '/_authenticated/dashboard/agents/new': {
      id: '/_authenticated/dashboard/agents/new'
      path: '/dashboard/agents/new'
      fullPath: '/dashboard/agents/new'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDashboardCallsRouteChildren {
  AuthenticatedDashboardCallsCallIdRoute: typeof AuthenticatedDashboardCallsCallIdRoute
}

const AuthenticatedDashboardCallsRouteChildren: AuthenticatedDashboardCallsRouteChildren =
  {
    AuthenticatedDashboardCallsCallIdRoute:
      AuthenticatedDashboardCallsCallIdRoute,
  }

const AuthenticatedDashboardCallsRouteWithChildren =
  AuthenticatedDashboardCallsRoute._addFileChildren(
    AuthenticatedDashboardCallsRouteChildren,
  )

interface AuthenticatedDashboardSchedulesRouteChildren {
  AuthenticatedDashboardSchedulesIdRoute: typeof AuthenticatedDashboardSchedulesIdRoute
}

const AuthenticatedDashboardSchedulesRouteChildren: AuthenticatedDashboardSchedulesRouteChildren =
  {
    AuthenticatedDashboardSchedulesIdRoute:
      AuthenticatedDashboardSchedulesIdRoute,
  }

const AuthenticatedDashboardSchedulesRouteWithChildren =
  AuthenticatedDashboardSchedulesRoute._addFileChildren(
    AuthenticatedDashboardSchedulesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardAlertingRoute: typeof AuthenticatedDashboardAlertingRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardBatchCallRoute: typeof AuthenticatedDashboardBatchCallRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardCallsRoute: typeof AuthenticatedDashboardCallsRouteWithChildren
  AuthenticatedDashboardChatHistoryRoute: typeof AuthenticatedDashboardChatHistoryRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardKnowledgeBaseRoute: typeof AuthenticatedDashboardKnowledgeBaseRoute
  AuthenticatedDashboardOutboundRoute: typeof AuthenticatedDashboardOutboundRoute
  AuthenticatedDashboardPhoneNumbersRoute: typeof AuthenticatedDashboardPhoneNumbersRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardQaRoute: typeof AuthenticatedDashboardQaRoute
  AuthenticatedDashboardSchedulesRoute: typeof AuthenticatedDashboardSchedulesRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardWorkflowsRoute: typeof AuthenticatedDashboardWorkflowsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAgentsNewRoute: typeof AuthenticatedDashboardAgentsNewRoute
  AuthenticatedDashboardAgentsIndexRoute: typeof AuthenticatedDashboardAgentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardAlertingRoute: AuthenticatedDashboardAlertingRoute,
  AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
  AuthenticatedDashboardBatchCallRoute: AuthenticatedDashboardBatchCallRoute,
  AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
  AuthenticatedDashboardCallsRoute:
    AuthenticatedDashboardCallsRouteWithChildren,
  AuthenticatedDashboardChatHistoryRoute:
    AuthenticatedDashboardChatHistoryRoute,
  AuthenticatedDashboardIntegrationsRoute:
    AuthenticatedDashboardIntegrationsRoute,
  AuthenticatedDashboardKnowledgeBaseRoute:
    AuthenticatedDashboardKnowledgeBaseRoute,
  AuthenticatedDashboardOutboundRoute: AuthenticatedDashboardOutboundRoute,
  AuthenticatedDashboardPhoneNumbersRoute:
    AuthenticatedDashboardPhoneNumbersRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardQaRoute: AuthenticatedDashboardQaRoute,
  AuthenticatedDashboardSchedulesRoute:
    AuthenticatedDashboardSchedulesRouteWithChildren,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardWorkflowsRoute: AuthenticatedDashboardWorkflowsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAgentsNewRoute: AuthenticatedDashboardAgentsNewRoute,
  AuthenticatedDashboardAgentsIndexRoute:
    AuthenticatedDashboardAgentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  DocsRoute: DocsRoute,
  DpaRoute: DpaRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  SdksRoute: SdksRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  VoiceSsoRoute: VoiceSsoRoute,
  Voice_ssoRoute: Voice_ssoRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
